steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/gcp-demo-project-415805/gcp-kubernetes/quickstart-image', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'us-east4-docker.pkg.dev/gcp-demo-project-415805/gcp-kubernetes/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/gcp-demo-project-415805/gcp-kubernetes/quickstart-image' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/gcp-demo-project-415805/gcp-kubernetes/flask-image', './app2' ]
  id: 'Build Docker Image2'

  # images:
  # - 'us-east4-docker.pkg.dev/gcp-demo-project-415805/gcp-kubernetes/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/gcp-demo-project-415805/gcp-kubernetes/flask-image' ]
  id: 'Push Docker Image2'


- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-east4
    gcloud deploy apply --file deploy/dev.yaml --region=us-east4
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-east4 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY
